using Baihua.Core.Models;
using Baihua.Core.Services;
using Microsoft.EntityFrameworkCore;
using Baihua.Data;

namespace Baihua.Modules.Family.Services;

public class StartupOrchestratorHostedService : IHostedService
{
    private readonly IDbContextFactory<FamilyDbContext> _familyDbContextFactory;
    private readonly IDbContextFactory<VaultDbContext> _vaultDbContextFactory;
    private readonly VaultSettingsService _vaultSettings;
    private readonly ILogger<StartupOrchestratorHostedService> _logger;

    public StartupOrchestratorHostedService(
        IDbContextFactory<FamilyDbContext> familyDbContextFactory,
        IDbContextFactory<VaultDbContext> vaultDbContextFactory,
        VaultSettingsService vaultSettings,
        ILogger<StartupOrchestratorHostedService> logger)
    {
        _familyDbContextFactory = familyDbContextFactory;
        _vaultDbContextFactory = vaultDbContextFactory;
        _vaultSettings = vaultSettings;
        _logger = logger;
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        try
        {
            LoadFromDatabase();
            TrySyncVaultsOnStartup();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "启动编排部分失败，已记录错误但继续启动应用");
        }

        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }

    private void LoadFromDatabase()
    {
        // PostgreSQL：EnsureCreated 生成完整 schema（一服务一数据库，无迁移历史）
        TryEnsureCreated("Family", () =>
        {
            using var familyDb = _familyDbContextFactory.CreateDbContext();
            familyDb.Database.EnsureCreated();
            // 存量库兼容：EnsureCreated 对已存在的库不补建新表，
            // 家庭病历本的表用幂等 DDL 补齐（与 EF 模型保持一致，重复执行安全）。
            EnsureMedicalTables(familyDb);
            EnsureLocalModelRegistryTable(familyDb);
            // 并发初始化会插入重复的服务器身份（各自生成不同共享密钥）：
            // 去重后加唯一索引，避免移动端按 A 密钥配对、服务端按 B 密钥验签。
            EnsureSingleServerIdentity(familyDb);
        });

        TryEnsureCreated("Vault", () =>
        {
            using var vaultDb = _vaultDbContextFactory.CreateDbContext();
            vaultDb.Database.EnsureCreated();
            // 并发扫描会重复登记同一知识库（界面出现重复卡片）：
            // 去重 + 迁移 id 命名的历史知识库 + 加条件唯一索引。
            EnsureVaultsUniqueAndMigrateLegacy(vaultDb);
        });

        // AI 库 schema 与 API Key 加密密钥迁移完全归 AI 服务独占（一服务一数据库）：
        // Family 不再等待/检查 ai.db，也不再参与 key 迁移（Family 不持有/不解密 key）。
    }

    /// <summary>
    /// 幂等创建家庭病历本相关表（PostgreSQL DDL，与 FamilyDbContext 模型一致）。
    /// EnsureCreated 只在库不存在时建表，已部署的库需此处补齐新增表。
    /// </summary>
    private static void EnsureMedicalTables(FamilyDbContext db)
    {
        const string ddl = """
            CREATE TABLE IF NOT EXISTS "MedicalMembers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "Name" text NOT NULL,
                "Gender" text NOT NULL DEFAULT '',
                "BirthDate" timestamp with time zone NULL,
                "BloodType" text NOT NULL DEFAULT '',
                "AllergiesJson" text NOT NULL DEFAULT '[]',
                "ChronicDiseasesJson" text NOT NULL DEFAULT '[]',
                "Notes" text NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_MedicalMembers" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_MedicalMembers_Name" ON "MedicalMembers" ("Name");

            CREATE TABLE IF NOT EXISTS "MedicalRecords" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "MemberId" integer NOT NULL,
                "OccurredAt" timestamp with time zone NOT NULL,
                "Title" text NOT NULL,
                "SymptomsJson" text NOT NULL DEFAULT '[]',
                "DiagnosesJson" text NOT NULL DEFAULT '[]',
                "MedicationsJson" text NOT NULL DEFAULT '[]',
                "Notes" text NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_MedicalRecords" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_MedicalRecords_MedicalMembers_MemberId" FOREIGN KEY ("MemberId")
                    REFERENCES "MedicalMembers" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_MemberId" ON "MedicalRecords" ("MemberId");
            CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_OccurredAt" ON "MedicalRecords" ("OccurredAt");

            CREATE TABLE IF NOT EXISTS "AiDiagnoses" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "MemberId" integer NOT NULL,
                "SymptomText" text NOT NULL,
                "AiResponse" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_AiDiagnoses" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AiDiagnoses_MedicalMembers_MemberId" FOREIGN KEY ("MemberId")
                    REFERENCES "MedicalMembers" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_AiDiagnoses_MemberId" ON "AiDiagnoses" ("MemberId");
            CREATE INDEX IF NOT EXISTS "IX_AiDiagnoses_MemberId_CreatedAt" ON "AiDiagnoses" ("MemberId", "CreatedAt");
            ALTER TABLE "AiDiagnoses" ADD COLUMN IF NOT EXISTS "ModelUsed" text NOT NULL DEFAULT 'main';
            ALTER TABLE "AiDiagnoses" ADD COLUMN IF NOT EXISTS "StructuredResultJson" text NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "HeightCm" double precision NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "WeightKg" double precision NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "Occupation" text NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "LifeHabits" text NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "SportsInjuriesJson" text NOT NULL DEFAULT '[]';
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "ConstitutionJson" text NULL;
            ALTER TABLE "MedicalRecords" ADD COLUMN IF NOT EXISTS "FourDiagnosticsJson" text NULL;
            """;
        db.Database.ExecuteSqlRaw(ddl);
    }

    /// <summary>
    /// 幂等创建本地大模型注册表（PostgreSQL DDL，与 FamilyDbContext 模型一致）。
    /// Agent 经 MCP 写入，WebUI 只读；存量库需此处补齐。
    /// </summary>
    private static void EnsureLocalModelRegistryTable(FamilyDbContext db)
    {
        const string ddl = """
            CREATE TABLE IF NOT EXISTS "LocalModelRegistries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "Tool" text NOT NULL,
                "ModelId" text NOT NULL,
                "DisplayName" text NOT NULL,
                "Endpoint" text NOT NULL,
                "ParameterSize" text NULL,
                "Quantization" text NULL,
                "Usage" text NULL,
                "SizeBytes" bigint NULL,
                "Capabilities" text NULL,
                "Notes" text NULL,
                "RegisteredBy" text NOT NULL DEFAULT '',
                "RegisteredAt" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_LocalModelRegistries" PRIMARY KEY ("Id")
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_LocalModelRegistries_Tool_ModelId"
                ON "LocalModelRegistries" ("Tool", "ModelId");
            """;
        db.Database.ExecuteSqlRaw(ddl);
    }

    /// <summary>
    /// 保证「整个百花只有一份服务器身份」。启动期并发调用 GetSettings 会各插一条
    /// （带各自的共享密钥），移动端可能按其中一条配对、服务端按另一条验签，
    /// 结果是配对成功但所有签名请求 401（花记看不到知识库列表）。
    /// 幂等：仅保留 Id 最小的一条，其余并入后删除，再建唯一索引防复发。
    /// </summary>
    private void EnsureSingleServerIdentity(FamilyDbContext db)
    {
        const string ddl = """
            WITH ranked AS (
                SELECT "Id", ROW_NUMBER() OVER (ORDER BY "Id") AS rn
                FROM "ServerAddressSettings"
            )
            DELETE FROM "ServerAddressSettings" s
            USING ranked r
            WHERE s."Id" = r."Id" AND r.rn > 1;
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_ServerAddressSettings_ServerInstanceId"
                ON "ServerAddressSettings" ("ServerInstanceId")
                WHERE "ServerInstanceId" IS NOT NULL AND "ServerInstanceId" <> '';
            """;
        db.Database.ExecuteSqlRaw(ddl);
    }

    /// <summary>
    /// 知识库去重 + 历史遗留目录迁移 + 加条件唯一索引。
    ///
    /// 背景：`SyncVaultsWithFilesystem` 是 check-then-insert，无唯一约束；
    /// 并发的两次扫描会重复登记同一路径，界面上同一条知识库出现两张卡片。
    /// 另：旧版移动端上传目录 `mobile-uploads/{id}` 会被扫描器当成本地知识库，
    /// 名字取目录名（一串 id），需要迁移到当前的 &lt;root&gt;/mobile/&lt;名称&gt; 约定。
    ///
    /// 幂等：重复执行无副作用。删除重复行前先把引用它的子表指到保留行，避免丢数据。
    /// </summary>
    private void EnsureVaultsUniqueAndMigrateLegacy(VaultDbContext db)
    {
        // 1) 迁移 id 命名 / 旧 mobile-uploads 结构的知识库（改名 + 移动目录）
        MigrateLegacyVaultNames(db);

        // 2) 去重：每个 Path 保留 Id 最小的一条，其余子表改指后删除
        const string dedupeDdl = """
            CREATE TEMP TABLE _dup_vaults ON COMMIT DROP AS
            SELECT "Id" AS dup_id, MIN("Id") OVER (PARTITION BY "Path") AS keep_id
            FROM "Vaults" WHERE "IsDeleted" = false;

            DELETE FROM _dup_vaults WHERE dup_id = keep_id;

            DO $$
            DECLARE r RECORD; c RECORD;
            BEGIN
                FOR r IN SELECT dup_id, keep_id FROM _dup_vaults LOOP
                    FOR c IN
                        SELECT table_name FROM information_schema.columns
                        WHERE table_schema = 'public' AND column_name = 'VaultId'
                          AND table_name <> 'Vaults'
                    LOOP
                        EXECUTE format(
                            'UPDATE %I SET "VaultId" = $1::text WHERE "VaultId" = $2::text',
                            c.table_name) USING r.keep_id, r.dup_id;
                    END LOOP;
                END LOOP;
            END $$;

            DELETE FROM "Vaults" v USING _dup_vaults d WHERE v."Id" = d.dup_id;
            """;
        db.Database.ExecuteSqlRaw(dedupeDdl);

        // 3) 条件唯一索引：未删除的知识库，路径与名称都唯一（回收站不受限）。
        // 单独 try：索引建不上（存量脏数据）不应连累启动，只需记警告。
        // 数据侧由 SyncVaultsWithFilesystem 串行锁 + 扫描跳过遗留目录保证不再产生重复。
        try
        {
            const string indexDdl = """
                CREATE UNIQUE INDEX IF NOT EXISTS "UX_Vaults_Path_Active"
                    ON "Vaults" ("Path") WHERE "IsDeleted" = false;
                CREATE UNIQUE INDEX IF NOT EXISTS "UX_Vaults_Name_Active"
                    ON "Vaults" ("Name") WHERE "IsDeleted" = false;
                """;
            db.Database.ExecuteSqlRaw(indexDdl);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Vaults 唯一索引创建失败（存量重复数据），已跳过");
        }
    }

    /// <summary>
    /// 把「名字是 32 位 id」的历史知识库改成可读名称，并迁移到当前移动端目录约定。
    /// 旧版移动端上传落在 <c>&lt;root&gt;/mobile-uploads/&lt;id&gt;</c>，目录名即 vault id。
    ///
    /// 关键点：同一个 Path 往往有重复行，必须整组一起处理，否则只改了其中一行、
    /// 分组被拆开，后续按 Path 去重就失效了（会出现一行新路径 + 一行旧路径）。
    /// 只更新 Id 最小的那一行为目标名/新路径，其余重复行由去重步骤删除，
    /// 这样也不会触碰「未删除名称唯一」索引。
    /// </summary>
    private void MigrateLegacyVaultNames(VaultDbContext db)
    {
        var legacy = db.Vaults
            .Where(v => !v.IsDeleted)
            .ToList()
            .Where(v => System.Text.RegularExpressions.Regex.IsMatch(v.Name ?? "", "^[0-9a-fA-F]{32}$"))
            .ToList();
        if (legacy.Count == 0) return;

        var root = Baihua.Contracts.BaihuaPaths.Vaults;
        var changed = false;

        foreach (var group in legacy.GroupBy(v => v.Path))
        {
            var canonical = group.OrderBy(v => v.Id).First();
            var parentName = Path.GetFileName(Path.GetDirectoryName(canonical.Path) ?? "") ?? "";
            var isLegacyUpload = parentName.Equals("mobile-uploads", StringComparison.OrdinalIgnoreCase);
            var baseName = isLegacyUpload ? "移动上传" : "移动端知识库";

            // 目标名需在未删除集合内唯一（排除本组自身的重复行）
            var groupIds = group.Select(v => v.Id).ToHashSet();
            var name = baseName;
            var suffix = 2;
            while (db.Vaults.Any(v => !v.IsDeleted && !groupIds.Contains(v.Id) && v.Name == name))
            {
                name = $"{baseName}{suffix++}";
            }

            var newPath = canonical.Path;
            if (isLegacyUpload)
            {
                // 简化显示：按备注取一个可读名字（取自「某症的常见病因」这类标题）
                var note = Directory.Exists(Path.Combine(canonical.Path, "notes"))
                    ? Directory.EnumerateFiles(Path.Combine(canonical.Path, "notes"), "*.md", SearchOption.AllDirectories).FirstOrDefault()
                    : null;
                if (note != null)
                {
                    var m = System.Text.RegularExpressions.Regex.Match(
                        Path.GetFileNameWithoutExtension(note), @"^(.+?)的(常见病因|辨证分型|病因病机|治则治法|诊断方法|养生调护|外治法|方剂与药物|基础概念|关联与区别|预防调护)");
                    if (m.Success && m.Groups[1].Value.Length is > 0 and <= 12)
                    {
                        name = m.Groups[1].Value;
                    }
                }

                var targetDir = Path.Combine(root, "mobile", name.Length > 80 ? name[..80] : name);
                try
                {
                    if (Directory.Exists(canonical.Path) && !Directory.Exists(targetDir))
                    {
                        Directory.CreateDirectory(Path.GetDirectoryName(targetDir)!);
                        Directory.Move(canonical.Path, targetDir);
                        newPath = targetDir;
                    }
                    else if (Directory.Exists(targetDir))
                    {
                        newPath = targetDir;
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "迁移历史移动端知识库目录失败，仅改数据库名称: {Path}", canonical.Path);
                }
            }

            _logger.LogInformation("迁移历史知识库: \"{OldName}\" -> \"{NewName}\" ({OldPath} -> {NewPath})",
                canonical.Name, name, canonical.Path, newPath);

            canonical.Name = name;
            canonical.Path = newPath;
            if (isLegacyUpload)
            {
                canonical.Source = "mobile";
                canonical.Industry = "mobile";
                canonical.IsActive = true;
            }
            canonical.UpdatedAt = DateTime.UtcNow;
            changed = true;
        }

        if (changed) db.SaveChanges();
    }

    private void TryEnsureCreated(string domainName, Action action)
    {
        try
        {
            action();
            _logger.LogDebug("{Domain} 数据库初始化完成", domainName);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "{Domain} 数据库初始化失败: {Message}", domainName, ex.Message);
        }
    }

    private void TrySyncVaultsOnStartup()
    {
        var rootPath = _vaultSettings.VaultRootPathPreference;
        if (string.IsNullOrWhiteSpace(rootPath)) return;
        if (!Directory.Exists(rootPath)) return;

        try
        {
            var (added, removed) = _vaultSettings.SyncVaultsWithFilesystem(rootPath);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "启动时自动同步知识库失败");
        }
    }
}
