using Baihua.Core.Models;
using Baihua.Core.Services;
using Microsoft.EntityFrameworkCore;
using Baihua.Data;
using Baihua.AI.Provider;

namespace Baihua.Family.Services;

public class StartupOrchestratorHostedService : IHostedService
{
    private readonly IDbContextFactory<FamilyDbContext> _familyDbContextFactory;
    private readonly IDbContextFactory<VaultDbContext> _vaultDbContextFactory;
    private readonly VaultSettingsService _vaultSettings;
    private readonly LocalModelSettingsService _localModelSettings;
    private readonly ILogger<StartupOrchestratorHostedService> _logger;

    public StartupOrchestratorHostedService(
        IDbContextFactory<FamilyDbContext> familyDbContextFactory,
        IDbContextFactory<VaultDbContext> vaultDbContextFactory,
        VaultSettingsService vaultSettings,
        LocalModelSettingsService localModelSettings,
        ILogger<StartupOrchestratorHostedService> logger)
    {
        _familyDbContextFactory = familyDbContextFactory;
        _vaultDbContextFactory = vaultDbContextFactory;
        _vaultSettings = vaultSettings;
        _localModelSettings = localModelSettings;
        _logger = logger;
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        try
        {
            LoadFromDatabase();
            _localModelSettings.LoadLocalModelConfigFromFile();
            TrySyncVaultsOnStartup();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "启动编排部分失败，已记录错误但继续启动应用");
        }

        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }

    private void LoadFromDatabase()
    {
        // PostgreSQL：EnsureCreated 生成完整 schema（一服务一数据库，无迁移历史）
        TryEnsureCreated("Family", () =>
        {
            using var familyDb = _familyDbContextFactory.CreateDbContext();
            familyDb.Database.EnsureCreated();
            // 存量库兼容：EnsureCreated 对已存在的库不补建新表，
            // 家庭病历本的表用幂等 DDL 补齐（与 EF 模型保持一致，重复执行安全）。
            EnsureMedicalTables(familyDb);
            EnsureLocalModelRegistryTable(familyDb);
        });

        TryEnsureCreated("Vault", () =>
        {
            using var vaultDb = _vaultDbContextFactory.CreateDbContext();
            vaultDb.Database.EnsureCreated();
        });

        // AI 库 schema 与 API Key 加密密钥迁移完全归 AI 服务独占（一服务一数据库）：
        // Family 不再等待/检查 ai.db，也不再参与 key 迁移（Family 不持有/不解密 key）。
    }

    /// <summary>
    /// 幂等创建家庭病历本相关表（PostgreSQL DDL，与 FamilyDbContext 模型一致）。
    /// EnsureCreated 只在库不存在时建表，已部署的库需此处补齐新增表。
    /// </summary>
    private static void EnsureMedicalTables(FamilyDbContext db)
    {
        const string ddl = """
            CREATE TABLE IF NOT EXISTS "MedicalMembers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "Name" text NOT NULL,
                "Gender" text NOT NULL DEFAULT '',
                "BirthDate" timestamp with time zone NULL,
                "BloodType" text NOT NULL DEFAULT '',
                "AllergiesJson" text NOT NULL DEFAULT '[]',
                "ChronicDiseasesJson" text NOT NULL DEFAULT '[]',
                "Notes" text NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_MedicalMembers" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_MedicalMembers_Name" ON "MedicalMembers" ("Name");

            CREATE TABLE IF NOT EXISTS "MedicalRecords" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "MemberId" integer NOT NULL,
                "OccurredAt" timestamp with time zone NOT NULL,
                "Title" text NOT NULL,
                "SymptomsJson" text NOT NULL DEFAULT '[]',
                "DiagnosesJson" text NOT NULL DEFAULT '[]',
                "MedicationsJson" text NOT NULL DEFAULT '[]',
                "Notes" text NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_MedicalRecords" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_MedicalRecords_MedicalMembers_MemberId" FOREIGN KEY ("MemberId")
                    REFERENCES "MedicalMembers" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_MemberId" ON "MedicalRecords" ("MemberId");
            CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_OccurredAt" ON "MedicalRecords" ("OccurredAt");

            CREATE TABLE IF NOT EXISTS "AiDiagnoses" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "MemberId" integer NOT NULL,
                "SymptomText" text NOT NULL,
                "AiResponse" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_AiDiagnoses" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AiDiagnoses_MedicalMembers_MemberId" FOREIGN KEY ("MemberId")
                    REFERENCES "MedicalMembers" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_AiDiagnoses_MemberId" ON "AiDiagnoses" ("MemberId");
            CREATE INDEX IF NOT EXISTS "IX_AiDiagnoses_MemberId_CreatedAt" ON "AiDiagnoses" ("MemberId", "CreatedAt");
            ALTER TABLE "AiDiagnoses" ADD COLUMN IF NOT EXISTS "ModelUsed" text NOT NULL DEFAULT 'main';
            ALTER TABLE "AiDiagnoses" ADD COLUMN IF NOT EXISTS "StructuredResultJson" text NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "HeightCm" double precision NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "WeightKg" double precision NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "Occupation" text NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "LifeHabits" text NULL;
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "SportsInjuriesJson" text NOT NULL DEFAULT '[]';
            ALTER TABLE "MedicalMembers" ADD COLUMN IF NOT EXISTS "ConstitutionJson" text NULL;
            ALTER TABLE "MedicalRecords" ADD COLUMN IF NOT EXISTS "FourDiagnosticsJson" text NULL;
            """;
        db.Database.ExecuteSqlRaw(ddl);
    }

    /// <summary>
    /// 幂等创建本地大模型注册表（PostgreSQL DDL，与 FamilyDbContext 模型一致）。
    /// Agent 经 MCP 写入，WebUI 只读；存量库需此处补齐。
    /// </summary>
    private static void EnsureLocalModelRegistryTable(FamilyDbContext db)
    {
        const string ddl = """
            CREATE TABLE IF NOT EXISTS "LocalModelRegistries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "Tool" text NOT NULL,
                "ModelId" text NOT NULL,
                "DisplayName" text NOT NULL,
                "Endpoint" text NOT NULL,
                "ParameterSize" text NULL,
                "Quantization" text NULL,
                "Usage" text NULL,
                "SizeBytes" bigint NULL,
                "Capabilities" text NULL,
                "Notes" text NULL,
                "RegisteredBy" text NOT NULL DEFAULT '',
                "RegisteredAt" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_LocalModelRegistries" PRIMARY KEY ("Id")
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_LocalModelRegistries_Tool_ModelId"
                ON "LocalModelRegistries" ("Tool", "ModelId");
            """;
        db.Database.ExecuteSqlRaw(ddl);
    }

    private void TryEnsureCreated(string domainName, Action action)
    {
        try
        {
            action();
            _logger.LogDebug("{Domain} 数据库初始化完成", domainName);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "{Domain} 数据库初始化失败: {Message}", domainName, ex.Message);
        }
    }

    private void TrySyncVaultsOnStartup()
    {
        var rootPath = _vaultSettings.VaultRootPathPreference;
        if (string.IsNullOrWhiteSpace(rootPath)) return;
        if (!Directory.Exists(rootPath)) return;

        try
        {
            var (added, removed) = _vaultSettings.SyncVaultsWithFilesystem(rootPath);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "启动时自动同步知识库失败");
        }
    }
}
